version: '3.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PG_HOST=postgres
      - PG_USER=nest_project
      - PG_PASSWORD=secret
      - PG_DATABASE=tasksmanagement
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: nest_project
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tasksmanagement
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
