version: '3.0'

volumes:
  postgres-data:

networks:
  default:
    driver: bridge

services:

  postgres:
    image: postgres:latest
    env_file:
      - .development.env
    ports:
      - "5432:5432"
    environment:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .development.env
    ports:
      - "4000:4000"
      - "9229:9229"
    command: npm run start:dev
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - postgres